
void assert(bool); 

void assert(x!=0&&"Some Messege"); // to display a message at an error

// way to deal with exeptions

try //where your going to do something where it might cause a problem(you put try in main) 

throw//(you put throw in main)

catch//exeption that was thrown gets catched with the catch block(you put catch in main)


